/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.EventStore;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventStoreRecord extends UpdatableRecordImpl<EventStoreRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.event_store.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.event_store.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>account.event_store.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.event_store.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>account.event_store.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.event_store.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>account.event_store.event_type</code>.
     */
    public void setEventType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.event_store.event_type</code>.
     */
    public String getEventType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>account.event_store.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.event_store.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>account.event_store.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.event_store.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>account.event_store.event_id</code>.
     */
    public void setEventId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.event_store.event_id</code>.
     */
    public UUID getEventId() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventStoreRecord
     */
    public EventStoreRecord() {
        super(EventStore.EVENT_STORE);
    }

    /**
     * Create a detached, initialised EventStoreRecord
     */
    public EventStoreRecord(Long id, UUID accountId, Long version, String eventType, JSONB payload, OffsetDateTime createdAt, UUID eventId) {
        super(EventStore.EVENT_STORE);

        setId(id);
        setAccountId(accountId);
        setVersion(version);
        setEventType(eventType);
        setPayload(payload);
        setCreatedAt(createdAt);
        setEventId(eventId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EventStoreRecord
     */
    public EventStoreRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.EventStore value) {
        super(EventStore.EVENT_STORE);

        if (value != null) {
            setId(value.getId());
            setAccountId(value.getAccountId());
            setVersion(value.getVersion());
            setEventType(value.getEventType());
            setPayload(value.getPayload());
            setCreatedAt(value.getCreatedAt());
            setEventId(value.getEventId());
            resetChangedOnNotNull();
        }
    }
}
