/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.tables.Outbox;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxRecord extends UpdatableRecordImpl<OutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>account.outbox.outbox_id</code>.
     */
    public void setOutboxId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>account.outbox.outbox_id</code>.
     */
    public Long getOutboxId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>account.outbox.event_id</code>.
     */
    public void setEventId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>account.outbox.event_id</code>.
     */
    public UUID getEventId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>account.outbox.aggregate_type</code>.
     */
    public void setAggregateType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>account.outbox.aggregate_type</code>.
     */
    public String getAggregateType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>account.outbox.aggregate_id</code>.
     */
    public void setAggregateId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>account.outbox.aggregate_id</code>.
     */
    public UUID getAggregateId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>account.outbox.aggregate_version</code>.
     */
    public void setAggregateVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>account.outbox.aggregate_version</code>.
     */
    public Long getAggregateVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>account.outbox.event_type</code>.
     */
    public void setEventType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>account.outbox.event_type</code>.
     */
    public String getEventType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>account.outbox.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>account.outbox.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>account.outbox.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>account.outbox.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>account.outbox.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>account.outbox.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>account.outbox.publish_attempts</code>.
     */
    public void setPublishAttempts(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>account.outbox.publish_attempts</code>.
     */
    public Integer getPublishAttempts() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>account.outbox.last_error</code>.
     */
    public void setLastError(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>account.outbox.last_error</code>.
     */
    public String getLastError() {
        return (String) get(10);
    }

    /**
     * Setter for <code>account.outbox.available_at</code>.
     */
    public void setAvailableAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>account.outbox.available_at</code>.
     */
    public OffsetDateTime getAvailableAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>account.outbox.published_at</code>.
     */
    public void setPublishedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>account.outbox.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutboxRecord
     */
    public OutboxRecord() {
        super(Outbox.OUTBOX);
    }

    /**
     * Create a detached, initialised OutboxRecord
     */
    public OutboxRecord(Long outboxId, UUID eventId, String aggregateType, UUID aggregateId, Long aggregateVersion, String eventType, OffsetDateTime occurredAt, JSONB payload, String status, Integer publishAttempts, String lastError, OffsetDateTime availableAt, OffsetDateTime publishedAt) {
        super(Outbox.OUTBOX);

        setOutboxId(outboxId);
        setEventId(eventId);
        setAggregateType(aggregateType);
        setAggregateId(aggregateId);
        setAggregateVersion(aggregateVersion);
        setEventType(eventType);
        setOccurredAt(occurredAt);
        setPayload(payload);
        setStatus(status);
        setPublishAttempts(publishAttempts);
        setLastError(lastError);
        setAvailableAt(availableAt);
        setPublishedAt(publishedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OutboxRecord
     */
    public OutboxRecord(org.girardsimon.wealthpay.account.jooq.tables.pojos.Outbox value) {
        super(Outbox.OUTBOX);

        if (value != null) {
            setOutboxId(value.getOutboxId());
            setEventId(value.getEventId());
            setAggregateType(value.getAggregateType());
            setAggregateId(value.getAggregateId());
            setAggregateVersion(value.getAggregateVersion());
            setEventType(value.getEventType());
            setOccurredAt(value.getOccurredAt());
            setPayload(value.getPayload());
            setStatus(value.getStatus());
            setPublishAttempts(value.getPublishAttempts());
            setLastError(value.getLastError());
            setAvailableAt(value.getAvailableAt());
            setPublishedAt(value.getPublishedAt());
            resetChangedOnNotNull();
        }
    }
}
