/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventStore implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private UUID accountId;
    private Long version;
    private String eventType;
    private JSONB payload;
    private OffsetDateTime createdAt;
    private UUID eventId;

    public EventStore() {}

    public EventStore(EventStore value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.version = value.version;
        this.eventType = value.eventType;
        this.payload = value.payload;
        this.createdAt = value.createdAt;
        this.eventId = value.eventId;
    }

    public EventStore(
        Long id,
        UUID accountId,
        Long version,
        String eventType,
        JSONB payload,
        OffsetDateTime createdAt,
        UUID eventId
    ) {
        this.id = id;
        this.accountId = accountId;
        this.version = version;
        this.eventType = eventType;
        this.payload = payload;
        this.createdAt = createdAt;
        this.eventId = eventId;
    }

    /**
     * Getter for <code>account.event_store.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>account.event_store.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>account.event_store.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>account.event_store.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>account.event_store.version</code>.
     */
    public Long getVersion() {
        return this.version;
    }

    /**
     * Setter for <code>account.event_store.version</code>.
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * Getter for <code>account.event_store.event_type</code>.
     */
    public String getEventType() {
        return this.eventType;
    }

    /**
     * Setter for <code>account.event_store.event_type</code>.
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * Getter for <code>account.event_store.payload</code>.
     */
    public JSONB getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>account.event_store.payload</code>.
     */
    public void setPayload(JSONB payload) {
        this.payload = payload;
    }

    /**
     * Getter for <code>account.event_store.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>account.event_store.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>account.event_store.event_id</code>.
     */
    public UUID getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>account.event_store.event_id</code>.
     */
    public void setEventId(UUID eventId) {
        this.eventId = eventId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final EventStore other = (EventStore) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.version == null) {
            if (other.version != null)
                return false;
        }
        else if (!this.version.equals(other.version))
            return false;
        if (this.eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!this.eventType.equals(other.eventType))
            return false;
        if (this.payload == null) {
            if (other.payload != null)
                return false;
        }
        else if (!this.payload.equals(other.payload))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!this.eventId.equals(other.eventId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.version == null) ? 0 : this.version.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.payload == null) ? 0 : this.payload.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("EventStore (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(version);
        sb.append(", ").append(eventType);
        sb.append(", ").append(payload);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(eventId);

        sb.append(")");
        return sb.toString();
    }
}
