/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Outbox implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long outboxId;
    private UUID eventId;
    private String aggregateType;
    private UUID aggregateId;
    private Long aggregateVersion;
    private String eventType;
    private OffsetDateTime occurredAt;
    private JSONB payload;
    private String status;
    private Integer publishAttempts;
    private String lastError;
    private OffsetDateTime availableAt;
    private OffsetDateTime publishedAt;

    public Outbox() {}

    public Outbox(Outbox value) {
        this.outboxId = value.outboxId;
        this.eventId = value.eventId;
        this.aggregateType = value.aggregateType;
        this.aggregateId = value.aggregateId;
        this.aggregateVersion = value.aggregateVersion;
        this.eventType = value.eventType;
        this.occurredAt = value.occurredAt;
        this.payload = value.payload;
        this.status = value.status;
        this.publishAttempts = value.publishAttempts;
        this.lastError = value.lastError;
        this.availableAt = value.availableAt;
        this.publishedAt = value.publishedAt;
    }

    public Outbox(
        Long outboxId,
        UUID eventId,
        String aggregateType,
        UUID aggregateId,
        Long aggregateVersion,
        String eventType,
        OffsetDateTime occurredAt,
        JSONB payload,
        String status,
        Integer publishAttempts,
        String lastError,
        OffsetDateTime availableAt,
        OffsetDateTime publishedAt
    ) {
        this.outboxId = outboxId;
        this.eventId = eventId;
        this.aggregateType = aggregateType;
        this.aggregateId = aggregateId;
        this.aggregateVersion = aggregateVersion;
        this.eventType = eventType;
        this.occurredAt = occurredAt;
        this.payload = payload;
        this.status = status;
        this.publishAttempts = publishAttempts;
        this.lastError = lastError;
        this.availableAt = availableAt;
        this.publishedAt = publishedAt;
    }

    /**
     * Getter for <code>account.outbox.outbox_id</code>.
     */
    public Long getOutboxId() {
        return this.outboxId;
    }

    /**
     * Setter for <code>account.outbox.outbox_id</code>.
     */
    public void setOutboxId(Long outboxId) {
        this.outboxId = outboxId;
    }

    /**
     * Getter for <code>account.outbox.event_id</code>.
     */
    public UUID getEventId() {
        return this.eventId;
    }

    /**
     * Setter for <code>account.outbox.event_id</code>.
     */
    public void setEventId(UUID eventId) {
        this.eventId = eventId;
    }

    /**
     * Getter for <code>account.outbox.aggregate_type</code>.
     */
    public String getAggregateType() {
        return this.aggregateType;
    }

    /**
     * Setter for <code>account.outbox.aggregate_type</code>.
     */
    public void setAggregateType(String aggregateType) {
        this.aggregateType = aggregateType;
    }

    /**
     * Getter for <code>account.outbox.aggregate_id</code>.
     */
    public UUID getAggregateId() {
        return this.aggregateId;
    }

    /**
     * Setter for <code>account.outbox.aggregate_id</code>.
     */
    public void setAggregateId(UUID aggregateId) {
        this.aggregateId = aggregateId;
    }

    /**
     * Getter for <code>account.outbox.aggregate_version</code>.
     */
    public Long getAggregateVersion() {
        return this.aggregateVersion;
    }

    /**
     * Setter for <code>account.outbox.aggregate_version</code>.
     */
    public void setAggregateVersion(Long aggregateVersion) {
        this.aggregateVersion = aggregateVersion;
    }

    /**
     * Getter for <code>account.outbox.event_type</code>.
     */
    public String getEventType() {
        return this.eventType;
    }

    /**
     * Setter for <code>account.outbox.event_type</code>.
     */
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    /**
     * Getter for <code>account.outbox.occurred_at</code>.
     */
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }

    /**
     * Setter for <code>account.outbox.occurred_at</code>.
     */
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * Getter for <code>account.outbox.payload</code>.
     */
    public JSONB getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>account.outbox.payload</code>.
     */
    public void setPayload(JSONB payload) {
        this.payload = payload;
    }

    /**
     * Getter for <code>account.outbox.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>account.outbox.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>account.outbox.publish_attempts</code>.
     */
    public Integer getPublishAttempts() {
        return this.publishAttempts;
    }

    /**
     * Setter for <code>account.outbox.publish_attempts</code>.
     */
    public void setPublishAttempts(Integer publishAttempts) {
        this.publishAttempts = publishAttempts;
    }

    /**
     * Getter for <code>account.outbox.last_error</code>.
     */
    public String getLastError() {
        return this.lastError;
    }

    /**
     * Setter for <code>account.outbox.last_error</code>.
     */
    public void setLastError(String lastError) {
        this.lastError = lastError;
    }

    /**
     * Getter for <code>account.outbox.available_at</code>.
     */
    public OffsetDateTime getAvailableAt() {
        return this.availableAt;
    }

    /**
     * Setter for <code>account.outbox.available_at</code>.
     */
    public void setAvailableAt(OffsetDateTime availableAt) {
        this.availableAt = availableAt;
    }

    /**
     * Getter for <code>account.outbox.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return this.publishedAt;
    }

    /**
     * Setter for <code>account.outbox.published_at</code>.
     */
    public void setPublishedAt(OffsetDateTime publishedAt) {
        this.publishedAt = publishedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Outbox other = (Outbox) obj;
        if (this.outboxId == null) {
            if (other.outboxId != null)
                return false;
        }
        else if (!this.outboxId.equals(other.outboxId))
            return false;
        if (this.eventId == null) {
            if (other.eventId != null)
                return false;
        }
        else if (!this.eventId.equals(other.eventId))
            return false;
        if (this.aggregateType == null) {
            if (other.aggregateType != null)
                return false;
        }
        else if (!this.aggregateType.equals(other.aggregateType))
            return false;
        if (this.aggregateId == null) {
            if (other.aggregateId != null)
                return false;
        }
        else if (!this.aggregateId.equals(other.aggregateId))
            return false;
        if (this.aggregateVersion == null) {
            if (other.aggregateVersion != null)
                return false;
        }
        else if (!this.aggregateVersion.equals(other.aggregateVersion))
            return false;
        if (this.eventType == null) {
            if (other.eventType != null)
                return false;
        }
        else if (!this.eventType.equals(other.eventType))
            return false;
        if (this.occurredAt == null) {
            if (other.occurredAt != null)
                return false;
        }
        else if (!this.occurredAt.equals(other.occurredAt))
            return false;
        if (this.payload == null) {
            if (other.payload != null)
                return false;
        }
        else if (!this.payload.equals(other.payload))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.publishAttempts == null) {
            if (other.publishAttempts != null)
                return false;
        }
        else if (!this.publishAttempts.equals(other.publishAttempts))
            return false;
        if (this.lastError == null) {
            if (other.lastError != null)
                return false;
        }
        else if (!this.lastError.equals(other.lastError))
            return false;
        if (this.availableAt == null) {
            if (other.availableAt != null)
                return false;
        }
        else if (!this.availableAt.equals(other.availableAt))
            return false;
        if (this.publishedAt == null) {
            if (other.publishedAt != null)
                return false;
        }
        else if (!this.publishedAt.equals(other.publishedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.outboxId == null) ? 0 : this.outboxId.hashCode());
        result = prime * result + ((this.eventId == null) ? 0 : this.eventId.hashCode());
        result = prime * result + ((this.aggregateType == null) ? 0 : this.aggregateType.hashCode());
        result = prime * result + ((this.aggregateId == null) ? 0 : this.aggregateId.hashCode());
        result = prime * result + ((this.aggregateVersion == null) ? 0 : this.aggregateVersion.hashCode());
        result = prime * result + ((this.eventType == null) ? 0 : this.eventType.hashCode());
        result = prime * result + ((this.occurredAt == null) ? 0 : this.occurredAt.hashCode());
        result = prime * result + ((this.payload == null) ? 0 : this.payload.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.publishAttempts == null) ? 0 : this.publishAttempts.hashCode());
        result = prime * result + ((this.lastError == null) ? 0 : this.lastError.hashCode());
        result = prime * result + ((this.availableAt == null) ? 0 : this.availableAt.hashCode());
        result = prime * result + ((this.publishedAt == null) ? 0 : this.publishedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Outbox (");

        sb.append(outboxId);
        sb.append(", ").append(eventId);
        sb.append(", ").append(aggregateType);
        sb.append(", ").append(aggregateId);
        sb.append(", ").append(aggregateVersion);
        sb.append(", ").append(eventType);
        sb.append(", ").append(occurredAt);
        sb.append(", ").append(payload);
        sb.append(", ").append(status);
        sb.append(", ").append(publishAttempts);
        sb.append(", ").append(lastError);
        sb.append(", ").append(availableAt);
        sb.append(", ").append(publishedAt);

        sb.append(")");
        return sb.toString();
    }
}
