/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq;


import java.util.Arrays;
import java.util.List;

import org.girardsimon.wealthpay.account.jooq.tables.AccountBalanceView;
import org.girardsimon.wealthpay.account.jooq.tables.EventStore;
import org.girardsimon.wealthpay.account.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.account.jooq.tables.Outbox;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Account extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The table <code>account.account_balance_view</code>.
     */
    public final AccountBalanceView ACCOUNT_BALANCE_VIEW = AccountBalanceView.ACCOUNT_BALANCE_VIEW;

    /**
     * The table <code>account.event_store</code>.
     */
    public final EventStore EVENT_STORE = EventStore.EVENT_STORE;

    /**
     * The table <code>account.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>account.outbox</code>.
     */
    public final Outbox OUTBOX = Outbox.OUTBOX;

    /**
     * No further instances allowed
     */
    private Account() {
        super("account", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AccountBalanceView.ACCOUNT_BALANCE_VIEW,
            EventStore.EVENT_STORE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Outbox.OUTBOX
        );
    }
}
