/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq;


import org.girardsimon.wealthpay.account.jooq.tables.EventStore;
import org.girardsimon.wealthpay.account.jooq.tables.FlywaySchemaHistory;
import org.girardsimon.wealthpay.account.jooq.tables.Outbox;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in account.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_EVENT_STORE_ACCOUNT_ID_VERSION = Internal.createIndex(DSL.name("idx_event_store_account_id_version"), EventStore.EVENT_STORE, new OrderField[] { EventStore.EVENT_STORE.ACCOUNT_ID, EventStore.EVENT_STORE.VERSION }, false);
    public static final Index IDX_EVENT_STORE_EVENT_ID = Internal.createIndex(DSL.name("idx_event_store_event_id"), EventStore.EVENT_STORE, new OrderField[] { EventStore.EVENT_STORE.EVENT_ID }, true);
    public static final Index OUTBOX_AGGREGATE_ORDER_IDX = Internal.createIndex(DSL.name("outbox_aggregate_order_idx"), Outbox.OUTBOX, new OrderField[] { Outbox.OUTBOX.AGGREGATE_ID, Outbox.OUTBOX.AGGREGATE_VERSION }, false);
    public static final Index OUTBOX_PENDING_IDX = Internal.createIndex(DSL.name("outbox_pending_idx"), Outbox.OUTBOX, new OrderField[] { Outbox.OUTBOX.STATUS, Outbox.OUTBOX.AVAILABLE_AT, Outbox.OUTBOX.OUTBOX_ID }, false);
}
