/*
 * This file is generated by jOOQ.
 */
package org.girardsimon.wealthpay.account.jooq.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.girardsimon.wealthpay.account.jooq.Account;
import org.girardsimon.wealthpay.account.jooq.Indexes;
import org.girardsimon.wealthpay.account.jooq.Keys;
import org.girardsimon.wealthpay.account.jooq.tables.records.OutboxRecord;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Outbox extends TableImpl<OutboxRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>account.outbox</code>
     */
    public static final Outbox OUTBOX = new Outbox();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OutboxRecord> getRecordType() {
        return OutboxRecord.class;
    }

    /**
     * The column <code>account.outbox.outbox_id</code>.
     */
    public final TableField<OutboxRecord, Long> OUTBOX_ID = createField(DSL.name("outbox_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>account.outbox.event_id</code>.
     */
    public final TableField<OutboxRecord, UUID> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.outbox.aggregate_type</code>.
     */
    public final TableField<OutboxRecord, String> AGGREGATE_TYPE = createField(DSL.name("aggregate_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>account.outbox.aggregate_id</code>.
     */
    public final TableField<OutboxRecord, UUID> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>account.outbox.aggregate_version</code>.
     */
    public final TableField<OutboxRecord, Long> AGGREGATE_VERSION = createField(DSL.name("aggregate_version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>account.outbox.event_type</code>.
     */
    public final TableField<OutboxRecord, String> EVENT_TYPE = createField(DSL.name("event_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>account.outbox.occurred_at</code>.
     */
    public final TableField<OutboxRecord, OffsetDateTime> OCCURRED_AT = createField(DSL.name("occurred_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>account.outbox.payload</code>.
     */
    public final TableField<OutboxRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>account.outbox.status</code>.
     */
    public final TableField<OutboxRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>account.outbox.publish_attempts</code>.
     */
    public final TableField<OutboxRecord, Integer> PUBLISH_ATTEMPTS = createField(DSL.name("publish_attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>account.outbox.last_error</code>.
     */
    public final TableField<OutboxRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>account.outbox.available_at</code>.
     */
    public final TableField<OutboxRecord, OffsetDateTime> AVAILABLE_AT = createField(DSL.name("available_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>account.outbox.published_at</code>.
     */
    public final TableField<OutboxRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private Outbox(Name alias, Table<OutboxRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Outbox(Name alias, Table<OutboxRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>account.outbox</code> table reference
     */
    public Outbox(String alias) {
        this(DSL.name(alias), OUTBOX);
    }

    /**
     * Create an aliased <code>account.outbox</code> table reference
     */
    public Outbox(Name alias) {
        this(alias, OUTBOX);
    }

    /**
     * Create a <code>account.outbox</code> table reference
     */
    public Outbox() {
        this(DSL.name("outbox"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Account.ACCOUNT;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.OUTBOX_AGGREGATE_ORDER_IDX, Indexes.OUTBOX_PENDING_IDX);
    }

    @Override
    public Identity<OutboxRecord, Long> getIdentity() {
        return (Identity<OutboxRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<OutboxRecord> getPrimaryKey() {
        return Keys.OUTBOX_PKEY;
    }

    @Override
    public List<UniqueKey<OutboxRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.OUTBOX_EVENT_ID_KEY);
    }

    @Override
    public Outbox as(String alias) {
        return new Outbox(DSL.name(alias), this);
    }

    @Override
    public Outbox as(Name alias) {
        return new Outbox(alias, this);
    }

    @Override
    public Outbox as(Table<?> alias) {
        return new Outbox(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Outbox rename(String name) {
        return new Outbox(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Outbox rename(Name name) {
        return new Outbox(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Outbox rename(Table<?> name) {
        return new Outbox(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox where(Condition condition) {
        return new Outbox(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Outbox where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Outbox where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Outbox where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Outbox where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Outbox whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
