openapi: 3.1.0
info:
  title: WealthPay Account API
  version: 1.0.0
  description: API for account management in WealthPay.

servers:
  - url: http://localhost:8080
    description: Local dev

paths:
  /accounts:
    post:
      summary: Open new bank account
      operationId: openAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAccountResponse'

  /accounts/{id}:
    get:
      summary: Get the details of an account
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          description: Unique account identifier (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Account details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'

components:
  schemas:
    OpenAccountRequest:
      type: object
      required:
        - accountCurrency
        - initialAmount
        - initialAmountCurrency
      properties:
        accountCurrency:
          description: Currency of the account (base currency of all operations)
          $ref: '#/components/schemas/SupportedCurrency'
        initialAmount:
          type: number
          description: Initial money credited when opening the account
          minimum: 0
        initialAmountCurrency:
          description: Currency of the initial deposit
          $ref: '#/components/schemas/SupportedCurrency'

    OpenAccountResponse:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          format: uuid
          description: Unique identifier of the created account

    AccountResponse:
      type: object
      required:
        - id
        - currency
        - balanceAmount
        - reservedAmount
        - status
      properties:
        id:
          type: string
          format: uuid
        balanceAmount:
          type: number
          description: Current balance of the account
        currency:
          $ref: '#/components/schemas/SupportedCurrency'
          description: Currency of the account
        reservedAmount:
          type: number
          description: Amount reserved for future operations
        status:
          $ref: '#/components/schemas/AccountStatus'
          description: Current status of the account


    SupportedCurrency:
      type: string
      description: ISO 4217 currency code (e.g. USD, EUR, CHF)
      enum:
        - USD
        - AED
        - AUD
        - CAD
        - CHF
        - CNH
        - CZK
        - DKK
        - EUR
        - GBP
        - HKD
        - HUF
        - ILS
        - JPY
        - KRW
        - MXN
        - MYR
        - NOK
        - NZD
        - PLN
        - SAR
        - SEK
        - SGD
        - TRY
        - TWD
        - ZAR

    AccountStatus:
      type: string
      description: Current status of the account
      enum:
        - OPENED
        - CLOSED
