openapi: 3.1.0
info:
  title: WealthPay Account API
  version: 1.0.0
  description: API for account management in WealthPay.

servers:
  - url: http://localhost:8080
    description: Local dev

paths:
  /accounts:
    post:
      summary: Open new bank account
      operationId: openAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenAccountRequest'
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAccountResponse'

  /accounts/{id}:
    get:
      summary: Obtenir les détails d'un compte
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique du compte (UUID)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Compte trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '404':
          description: Compte introuvable

components:
  schemas:
    OpenAccountRequest:
      type: object
      required:
        - currency
        - initialBalance
      properties:
        currency:
          type: string
          description: ISO 4217 currency code (e.g. USD, EUR, CHF)
          pattern: '^[A-Z]{3}$'
          minLength: 3
          maxLength: 3
        initialBalance:
          type: number
          description: The initial account balance must be > 0
          minimum: 0
          exclusiveMinimum: true

    OpenAccountResponse:
      type: object
      required:
        - accountId
      properties:
        accountId:
          type: string
          format: uuid
          description: Unique identifier of the created account

    AccountResponse:
      type: object
      required:
        - id
        - currency
        - balance
      properties:
        id:
          type: string
          format: uuid
        currency:
          type: string
          minLength: 3
          maxLength: 3
        balance:
          type: number
          format: double